version: "3.7"

services:
  web:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "gunicorn project.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static:/app/static
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    build: ./data/nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static:/static

volumes:
  postgres_data:
  static:
